name       : python-llvmlite
version    : 0.34.0
release    : 7
source     :
    - https://github.com/numba/llvmlite/archive/v0.34.0.tar.gz : aea5c33d59145b96251d11971bad26d81810962ab683d107b6ef4a18472d3d9a
license    : BSD-2-Clause
homepage   : http://llvmlite.pydata.org
component  : programming.python
summary    : A lightweight LLVM python binding for writing JIT compilers
description: |
    llvmlite is a project originally tailored for Numba's needs, using the following approach:
        - small C wrapper around the parts of the LLVM C++ API we need that are not already exposed by the LLVM C API.
        - ctypes Python wrapper around the C API.
        - pure Python implementation of the subset of the LLVM IR builder that we need for Numba.
builddeps  :
    - llvm-devel
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # Tests can be reenabled when updated to 0.31.0
#    %python3_test -m llvmlite.tests
