name       : python-llvmlite
version    : 0.30.0
release    : 3
source     :
    - https://github.com/numba/llvmlite/archive/v0.30.0.tar.gz : 07b72dfdd8e6e5bc718fc7cd00517b94bf00caf29b387605adb0779c5c63dc28
license    : BSD-2-Clause
component  : programming.python
summary    : A lightweight LLVM python binding for writing JIT compilers
description: |
    llvmlite is a project originally tailored for Numba's needs, using the following approach:
        - small C wrapper around the parts of the LLVM C++ API we need that are not already exposed by the LLVM C API.
        - ctypes Python wrapper around the C API.
        - pure Python implementation of the subset of the LLVM IR builder that we need for Numba.
builddeps  :
    - llvm-devel
setup      : |
    %patch -p1 < $pkgfiles/ffi-cxx-flags.patch
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test -m llvmlite.tests
